### ISSUE TITLE
Doesn't show ESP8266's own IP address

### ISSUE THREAD

**Issue by domiflichi** [sleemanj/ESP8266_Simple#10]
First, let me say this looks like a great library for newbies like me.

So real quick here's my specs:
Arduino Duemilanove, Sparkfun Bi-Directional Logic Level Converter, ESP-01
Arduino software v1.6.5

When I try to run the 'GetIPAddress' sketch, this is what I get in the serial monitor:

---

ESP8266 Demo Sketch
Reset: OK
Connect: OK
IP Address: 0.0.0.0

The string IP is: 0.0.0.0
The unsigned long IP is: 0
The IP address 127.0.0.1 has integer value 2130706433
The integer value 921773419 has IP address 54.241.37.107
End of Demo

The string IP is: 0.0.0.0
The unsigned long IP is: 0
The IP address 127.0.0.1 has integer value 2130706433
The integer value 921773419 has IP address 54.241.37.107
End of Demo

---

(minus the asterisks of course)
And I just get that same 2nd paragraph on and on

However, I know the ESP-01 is getting an IP address because I can see it in my WiFi controller's software 'Client' list _and_ I can ping it.

**Comment by domiflichi** [comment]
Oh man, I feel dumb. I just read on your main Github page here how the format of the response when querying for the IP address has changed. So I must have a newer firmware like you mentioned there. So sorry about that.

**Comment by sleemanj** [comment]
Please read the Firmware Version Notes: 

https://github.com/sleemanj/ESP8266_Simple#firmware-version-patches-welcome
