### ISSUE TITLE
Trouble with reset: General Error

### ISSUE THREAD

**Issue by thekrustyclown** [sleemanj/ESP8266_Simple#14]
At first I was using the 3.3v power supply from the arduino, but the ESP8266 was constantly blinking red and giving me "reset: General Error". I ordered a part to step down the voltage from the arduino 5v to 3.3v, so i could supply enough current. The ESP built in LED is now a steady red, not blinking. I have updated the firmware to the current version, but I am still getting "reset: General Error". Any ideas? Thanks

**Comment by sleemanj** [comment]
The 5v regulator may be the limiting factor especially if you are powering other stuff from it or if capacitors are inadequate.

You'd really need to scope it to see.

First thing to try is add some bulk capacitance across Vcc and ground on the ESP.

In absence of a scope, setup a totally separate 3.3v supply (eg use batteries and a regulator) and use that to power the ESP (obviously connect grounds), see if that helps.
