### ISSUE TITLE
Problem with Reset

### ISSUE THREAD

**Issue by lorenzoferrante** [sleemanj/ESP8266_Simple#3]
I uploaded  the HelloWorld sketch and when I open the serial monitor here is what does it return to me:

---

ESP8266 Demo Sketch
## Reset: General Error

What am I doing wrong?
Thanks.

**Comment by Asoul** [comment]
Me too!
How to solve the problem?

**Comment by SiwyDym** [comment]
I have the same problem. Anyone know whats wrong?

**Comment by senro** [comment]
me too!

**Comment by sleemanj** [comment]
Check your power supply is strong enough, sagging power supply under load could be evidenced by resets.

Check firmware version.

I don't think this is a bug.

**Comment by Head** [comment]
Getting the same Error and finally fixed it: I've swapped RX and TX. Now it's kinda working... (Still no response)
