### ISSUE TITLE
Firmware AI-v0.9.5.0 AT

### ISSUE THREAD

**Issue by cyberlink1** [sleemanj/ESP8266_Simple#6]
Loaded the http_server sketch and get the following response

ESP8266 Demo Server Sketch
Reset: OK
Connect: Device issued "ready" unexpectedly (rebooted)
Connect: OK
IP Address: 0.0.0.0
Starting HTTP Server: OK
( Now you can use your web browser to hit the IP address above. )

uncommenting the delay in your code seems to fix that.

(code that I uncommented) 
  // delay(4000);
  // Once the reset is issued OK, try to issue an AT command
  // and wait until that works

However, it does not seem to work. It comes up and I locate the IP on my DHCP server be cause the code does not return an IP. When I connect to it, the port is open and available but I never get a response.

**Comment by domonetic** [comment]
same firmware, same problem.
Any solution?

**Comment by sleemanj** [comment]
See the main README.md, your firmware version is not currently supported
(maybe try other forks). Patches/pull requests welcome :-) 

On 2015-11-21 10:05, domonetic wrote: 

> same firmware, same problem.
> Any solution? 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].

## Links:

[1]
https://github.com/sleemanj/ESP8266_Simple/issues/6#issuecomment-158523188

**Comment by domonetic** [comment]
Where can find v.0.9.2.4?

**Comment by sleemanj** [comment]
Hmm, it looks like 0.9.2.4 has been eradicated from the internet!  I can't find it anywhere.  Perhaps ask at the esp8266.com forums, if you can find it, please let me know and I'll host it somewhere!

**Comment by sleemanj** [comment]
Support for 0.9.5.x has been added today.
