### ISSUE TITLE
Timeout Waiting For Response

### ISSUE THREAD

**Issue by sincetomorrow** [sleemanj/ESP8266_Simple#8]
Hi!

Your library is very simple and easy to use, I have been searching to find a simple on like that! 
I have a problem that the AT+CWJAP=.. command (wifi.setupAsWifiStation(ESP8266_SSID, ESP8266_PASS, &Serial);) shows me "Timeout Waiting For Response" error before actual connecting nu merous times. Is there a way to increase the timeout milliseconds?

Thanks,
Panos

**Comment by sleemanj** [comment]
Hi, you can use 

 wifi.setTimeout( [number of seconds] ); 

example 

 wifi.setTimeout(10); 

On 2015-09-02 08:32, Panos B wrote: 

> Hi! 
> 
> Your library is very simple and easy to use, I have been searching to find a simple on like that! 
> I have a problem that the AT+CWJAP=.. command (wifi.setupAsWifiStation(ESP8266_SSID, ESP8266_PASS, &Serial);) shows me "Timeout Waiting For Response" error before actual connecting nu merous times. Is there a way to increase the timeout milliseconds? 
> 
> Thanks,
> Panos 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].

## Links:

[1] https://github.com/sleemanj/ESP8266_Simple/issues/8

**Comment by sincetomorrow** [comment]
Thanks a lot! Should have known :-D
